# Generated by Django 6.0 on 2026-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_helpmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='helpmessage',
            new_name='security_he_recipie_6c912f_idx',
            old_name='security_he_recipient_2d3f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='helpmessage',
            new_name='security_he_sender__ed75db_idx',
            old_name='security_he_sender_54b02f_idx',
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado'), ('read', 'Leído'), ('attended', 'Atendido'), ('finalized', 'Finalizado')], default='sent', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
