# Generated by Django 6.0 on 2026-01-27 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_fix_timezone_fields'),
        ('employee', '0005_payrollinfo_roles_count'),
        ('institution', '0003_remove_deliverable_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Ej: ASC, NOM, REM', max_length=20, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Acción',
                'verbose_name_plural': 'Tipos de Acciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número de Acción')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explicación/Motivo')),
                ('date_issue', models.DateField(verbose_name='Fecha de Emisión')),
                ('date_effective', models.DateField(verbose_name='Rige a partir de')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Registrada')),
                ('date_registered', models.DateField(blank=True, null=True, verbose_name='Fecha de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel_actions.actiontype', verbose_name='Tipo de Acción')),
                ('authority_1', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='actions_signed_auth1', to='core.authorities', verbose_name='Primera Autoridad')),
                ('authority_2', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_signed_auth2', to='core.authorities', verbose_name='Segunda Autoridad')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_actions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('elaboration', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_elaboration', to='core.authorities', verbose_name='Elaborado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_actions', to='employee.employee', verbose_name='Empleado')),
                ('register', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_register', to='core.authorities', verbose_name='Registrado   por')),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_reviewed', to='core.authorities', verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Acción de Personal',
                'verbose_name_plural': 'Acciones de Personal',
                'ordering': ['-date_issue', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ActionMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_remuneration', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RMU Anterior')),
                ('new_remuneration', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RMU Nuevo')),
                ('location_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de Trabajo')),
                ('new_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to_pos', to='core.catalogitem', verbose_name='Puesto Nuevo')),
                ('new_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='institution.administrativeunit', verbose_name='Unidad Nueva')),
                ('previous_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from_pos', to='core.catalogitem', verbose_name='Puesto Anterior')),
                ('previous_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='institution.administrativeunit', verbose_name='Unidad Anterior')),
                ('personnel_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='personnel_actions.personnelaction')),
            ],
            options={
                'verbose_name': 'Detalle del Movimiento',
                'verbose_name_plural': 'Detalles de Movimientos',
            },
        ),
    ]
