# Generated by Django 6.0 on 2026-02-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelaction',
            name='motivation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivación'),
        ),
    ]
