# Generated by Django 6.0 on 2026-03-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authority_model_migration'),
        ('personnel_actions', '0002_personnelaction_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelaction',
            name='authority_1',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='actions_signed_auth1', to='core.authority', verbose_name='Primera Autoridad'),
        ),
        migrations.AlterField(
            model_name='personnelaction',
            name='authority_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_signed_auth2', to='core.authority', verbose_name='Segunda Autoridad'),
        ),
        migrations.AlterField(
            model_name='personnelaction',
            name='elaboration',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_elaboration', to='core.authority', verbose_name='Elaborado por'),
        ),
        migrations.AlterField(
            model_name='personnelaction',
            name='register',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_register', to='core.authority', verbose_name='Registrado   por'),
        ),
        migrations.AlterField(
            model_name='personnelaction',
            name='reviewer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_reviewed', to='core.authority', verbose_name='Revisado por'),
        ),
    ]
