# Generated by Django 6.0 on 2026-04-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetgroup_budgetline_budget_group'),
        ('personnel_actions', '0003_alter_personnelaction_authority_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmovement',
            name='new_budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to_budget', to='budget.budgetline', verbose_name='Partida Presupuestaria Nueva'),
        ),
        migrations.AddField(
            model_name='actionmovement',
            name='previous_budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from_budget', to='budget.budgetline', verbose_name='Partida Anterior'),
        ),
    ]
