# Generated by Django 6.0 on 2026-05-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0006_personnelaction_user_signers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='code',
            field=models.CharField(help_text='Ej: ASC, NOM, REM', max_length=35, unique=True, verbose_name='Código'),
        ),
    ]
