# Generated by Django 6.0 on 2026-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0007_alter_actiontype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmovement',
            name='new_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Puesto nuevo'),
        ),
        migrations.AlterField(
            model_name='actionmovement',
            name='new_unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad nueva'),
        ),
        migrations.AlterField(
            model_name='actionmovement',
            name='previous_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Puesto anterior'),
        ),
        migrations.AlterField(
            model_name='actionmovement',
            name='previous_unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad Administrativa anterior'),
        ),
    ]
