# Generated by Django 6.0 on 2026-05-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0008_alter_actionmovement_new_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelaction',
            name='date_effective',
            field=models.DateField(blank=True, null=True, verbose_name='Rige a partir de'),
        ),
        migrations.AlterField(
            model_name='personnelaction',
            name='date_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión'),
        ),
    ]
