# Generated by Django 6.0 on 2026-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0009_alter_personnelaction_date_effective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
