# Generated by Django 6.0 on 2026-06-10 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0010_personnelaction_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='default_authority_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_auth1_types', to=settings.AUTH_USER_MODEL, verbose_name='Autoridad 1 (Defecto)'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='default_authority_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_auth2_types', to=settings.AUTH_USER_MODEL, verbose_name='Autoridad 2 (Defecto)'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='default_register',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_register_types', to=settings.AUTH_USER_MODEL, verbose_name='Registrador (Defecto)'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='default_reviewer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_reviewer_types', to=settings.AUTH_USER_MODEL, verbose_name='Revisor (Defecto)'),
        ),
    ]
