# Generated by Django 6.0 on 2026-07-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0011_actiontype_default_authority_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmovement',
            name='personnel_action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='personnel_actions.personnelaction'),
        ),
    ]
