# Generated by Django 6.0 on 2026-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0012_alter_actionmovement_personnel_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='is_acting',
            field=models.BooleanField(default=False, help_text='Marcar si es un movimiento temporal donde no se altera la partida titular del empleado ni del custodio.', verbose_name='Es Encargo / Subrogación'),
        ),
    ]
