# Generated by Django 6.0 on 2026-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0013_actiontype_is_acting'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='is_acting_termination',
            field=models.BooleanField(default=False, help_text='Finaliza el encargo activo y devuelve al servidor a su partida titular.', verbose_name='Es Conclusión de Encargo / Reintegro'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='requires_budget_movement',
            field=models.BooleanField(default=False, help_text='Activa el selector de partida presupuestaria (traslado, ascenso, encargo, etc.).', verbose_name='Requiere Movimiento de Partida'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='requires_unit_movement',
            field=models.BooleanField(default=False, help_text='Activa el selector de unidad administrativa / dependencia en cascada.', verbose_name='Requiere Reubicación de Unidad'),
        ),
    ]
