# Generated by Django 6.0 on 2026-04-06

import django.db.models.deletion
import employee_archive.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_alter_payrollinfo_education_dependents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('is_required', models.BooleanField(default=False, verbose_name='Requisito de ingreso')),
                ('has_expiration', models.BooleanField(default=False, verbose_name='Requiere fecha de caducidad')),
                ('max_size_mb', models.PositiveIntegerField(default=10, verbose_name='Tamano maximo (MB)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_archive_employeedocumenttype_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_archive_employeedocumenttype_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Empleado',
                'verbose_name_plural': 'Tipos de Documentos de Empleado',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('OBSERVED', 'Observado')], default='PENDING', max_length=12, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_archive_employeearchivedocument_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents', to='employee_archive.employeedocumenttype', verbose_name='Tipo de Documento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_documents', to='employee.employee', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_archive_employeearchivedocument_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Documento de Archivo Digital',
                'verbose_name_plural': 'Documentos de Archivo Digital',
                'ordering': ['employee__person__last_name', 'document_type__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeArchiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('file', models.FileField(upload_to=employee_archive.models.employee_archive_upload_path, verbose_name='Archivo PDF')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emision')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('is_current', models.BooleanField(default=True, verbose_name='Version vigente')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='employee_archive.employeearchivedocument', verbose_name='Documento Archivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_archive_employeearchiveversion_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_archive_employeearchiveversion_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_archive_versions', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Version de Documento',
                'verbose_name_plural': 'Versiones de Documento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeearchivedocument',
            constraint=models.UniqueConstraint(fields=('employee', 'document_type'), name='unique_employee_document_type_archive'),
        ),
        migrations.AddConstraint(
            model_name='employeearchiveversion',
            constraint=models.UniqueConstraint(fields=('archive', 'version_number'), name='unique_archive_version_number'),
        ),
        migrations.AddConstraint(
            model_name='employeearchiveversion',
            constraint=models.UniqueConstraint(condition=models.Q(is_current=True), fields=('archive',), name='unique_current_version_per_archive'),
        ),
    ]
