# Generated by Django 6.0 on 2026-02-11 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_payrollinfo_roles_count'),
        ('personnel_actions', '0002_personnelaction_motivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de sanción')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='¿Requiere adjunto?')),
            ],
            options={
                'verbose_name': 'Tipo de Sanción',
                'verbose_name_plural': 'Tipos de Sanciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_number', models.CharField(max_length=50, unique=True, verbose_name='Número de sanción')),
                ('severity', models.CharField(choices=[('MINOR', 'Leve'), ('MODERATE', 'Moderada'), ('SEVERE', 'Grave'), ('VERY_SEVERE', 'Muy Grave')], default='MINOR', max_length=20, verbose_name='Gravedad')),
                ('description', models.TextField(verbose_name='Descripción de la falta')),
                ('legal_basis', models.TextField(blank=True, null=True, verbose_name='Base legal')),
                ('incident_date', models.DateField(verbose_name='Fecha del incidente')),
                ('sanction_date', models.DateField(verbose_name='Fecha de la sanción')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('days', models.IntegerField(default=0, verbose_name='Días de suspensión')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registrada'), ('ACTIVE', 'Activa'), ('COMPLETED', 'Cumplida'), ('CANCELED', 'Anulada')], default='REGISTERED', max_length=20, verbose_name='Estado')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='documents/sanctions/%Y/%m/', verbose_name='Documento adjunto')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to='employee.employee', verbose_name='Empleado')),
                ('personnel_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_sanctions', to='personnel_actions.personnelaction', verbose_name='Acción de Personal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('sanction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sanctions.sanctiontype', verbose_name='Tipo de Sanción')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'ordering': ['-sanction_date', '-sanction_number'],
                'indexes': [models.Index(fields=['employee', 'status'], name='sanctions_s_employe_69904a_idx'), models.Index(fields=['sanction_date'], name='sanctions_s_sanctio_10b58d_idx')],
            },
        ),
    ]
