# Generated by Django 6.0 on 2026-02-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanction',
            options={'ordering': ['-sanction_date', '-created_at'], 'verbose_name': 'Sanción', 'verbose_name_plural': 'Sanciones'},
        ),
        migrations.RemoveField(
            model_name='sanction',
            name='sanction_number',
        ),
        migrations.AlterField(
            model_name='sanction',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Días de suspensión'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='severity',
            field=models.CharField(choices=[('VERBAL_WARNING', 'Amonestación Verbal'), ('WRITTEN_WARNING', 'Amonestación Escrita'), ('PECUNIARY_WARNING', 'Amonestación Pecuniaria'), ('ADMINISTRATIVE_SUMMARY', 'Sumario Administrativo')], default='VERBAL_WARNING', max_length=30, verbose_name='Gravedad'),
        ),
    ]
