# Generated by Django 6.0 on 2026-04-08 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_managementperiod_manual_position_and_more'),
        ('sanctions', '0002_alter_sanction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionNotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=120, verbose_name='Tipo de notificación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SanctionNotificationTypeRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='documents/sanction_notifications/%Y/%m/', verbose_name='Formato Word')),
                ('labor_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_templates', to='contract.laborregime', verbose_name='Régimen laboral')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regime_templates', to='sanctions.sanctionnotificationtype', verbose_name='Tipo de notificación')),
            ],
            options={
                'verbose_name': 'Formato de notificación por régimen',
                'verbose_name_plural': 'Formatos de notificación por régimen',
                'ordering': ['labor_regime__name'],
                'unique_together': {('notification_type', 'labor_regime')},
            },
        ),
        migrations.AddField(
            model_name='sanctionnotificationtype',
            name='labor_regimes',
            field=models.ManyToManyField(blank=True, related_name='sanction_notification_types', through='sanctions.SanctionNotificationTypeRegime', to='contract.laborregime', verbose_name='Regímenes laborales'),
        ),
    ]
