# Generated by Django 6.0 on 2026-04-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_managementperiod_manual_position_and_more'),
        ('core', '0004_authority_model_migration'),
        ('employee', '0008_alter_payrollinfo_education_dependents_and_more'),
        ('sanctions', '0003_sanctionnotificationtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('registration_date', models.DateField(verbose_name='Fecha de registro')),
                ('minutes_late', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Minutos de atraso')),
                ('regs_without_mark', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Regs. sin marcar')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('generated_docx', models.FileField(blank=True, null=True, upload_to='documents/sanction_notifications/generated/%Y/%m/', verbose_name='Documento Word generado')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='documents/sanction_notifications/generated/%Y/%m/', verbose_name='Documento PDF generado')),
                ('authority_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_notifications_authority_1', to='core.authority', verbose_name='Firma 1')),
                ('authority_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanction_notifications_authority_2', to='core.authority', verbose_name='Firma 2')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_notifications', to='employee.employee', verbose_name='Empleado')),
                ('labor_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_notifications', to='contract.laborregime', verbose_name='Régimen laboral')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='sanctions.sanctionnotificationtype', verbose_name='Tipo de notificación')),
                ('regime_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='sanctions.sanctionnotificationtyperegime', verbose_name='Formato por régimen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Notificación de Sanción',
                'verbose_name_plural': 'Notificaciones de Sanción',
                'ordering': ['-registration_date', '-created_at'],
            },
        ),
    ]
