# Generated by Django 6.0 on 2026-04-08 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0004_sanctionnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionNotificationTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=80, verbose_name='Marcador')),
                ('label', models.CharField(max_length=120, verbose_name='Nombre visible')),
                ('source_key', models.CharField(choices=[('employee_full_name', 'Nombre completo del empleado'), ('employee_first_name', 'Nombres del empleado'), ('employee_last_name', 'Apellidos del empleado'), ('employee_document_number', 'Documento del empleado'), ('employee_position', 'Cargo del empleado'), ('employee_unit', 'Unidad / área del empleado'), ('regime_code', 'Código del régimen'), ('regime_name', 'Nombre del régimen'), ('notification_name', 'Nombre del tipo de notificación'), ('month_name', 'Nombre del mes'), ('month_number', 'Número del mes'), ('year', 'Año'), ('registration_date', 'Fecha de registro'), ('authority_1_name', 'Nombre de la autoridad 1'), ('authority_1_position', 'Cargo de la autoridad 1'), ('authority_2_name', 'Nombre de la autoridad 2'), ('authority_2_position', 'Cargo de la autoridad 2'), ('minutes_late', 'Minutos de atraso'), ('regs_without_mark', 'Registros sin marcar'), ('observations', 'Observaciones')], max_length=60, verbose_name='Fuente de datos')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_mappings', to='sanctions.sanctionnotificationtype', verbose_name='Tipo de notificación')),
            ],
            options={
                'verbose_name': 'Mapeo de marcador',
                'verbose_name_plural': 'Mapeos de marcadores',
                'ordering': ['order', 'label'],
                'unique_together': {('notification_type', 'placeholder')},
            },
        ),
    ]
