# Generated by Django 6.0 on 2026-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0007_seed_notification_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionnotification',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Secuencia'),
        ),
        migrations.AddField(
            model_name='sanctionnotification',
            name='user_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=12, verbose_name='Código de usuario'),
        ),
    ]
