# Generated by Django 6.0 on 2026-04-08 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_managementperiod_manual_position_and_more'),
        ('sanctions', '0008_sanctionnotification_sequence_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('labor_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_notification_templates', to='contract.laborregime', verbose_name='Régimen laboral')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_templates', to='sanctions.sanctionnotificationtype', verbose_name='Tipo de notificación')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Template dinámico',
                'verbose_name_plural': 'Templates dinámicos',
                'ordering': ['labor_regime__code', 'notification_type__name'],
                'unique_together': {('notification_type', 'labor_regime')},
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('section_type', models.CharField(choices=[('PARAGRAPH', 'Párrafo (justificado)'), ('TITLE', 'Título (izquierda)')], default='PARAGRAPH', max_length=20, verbose_name='Tipo de sección')),
                ('content', models.TextField(help_text='Puede incluir variables: [FULL_NAME], [POSITION], [today], etc.', verbose_name='Contenido')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sanctions.notificationtemplate', verbose_name='Template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Sección de template',
                'verbose_name_plural': 'Secciones de template',
                'ordering': ['template', 'order'],
            },
        ),
    ]
