# Generated by Django 6.0 on 2026-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0009_notificationtemplate_templatesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionnotification',
            name='generated_docx',
        ),
        migrations.AlterField(
            model_name='sanctionnotificationtyperegime',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/sanction_notifications/%Y/%m/', verbose_name='Formato'),
        ),
    ]
