# Generated by Django 6.0 on 2026-04-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0010_remove_sanctionnotification_generated_docx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionnotificationtyperegime',
            name='template_file',
        ),
    ]
