# Generated by Django 6.0 on 2026-04-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0011_remove_sanctionnotificationtyperegime_template_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionnotification',
            name='authority_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanction_notifications_authority_1', to='core.authority', verbose_name='Firma 1'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE sanctions_sanctionnotification
                SET authority_1_id = NULL,
                    authority_2_id = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='sanctionnotification',
            name='authority_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanction_notifications_authority_1', to=settings.AUTH_USER_MODEL, verbose_name='Firma 1'),
        ),
        migrations.AlterField(
            model_name='sanctionnotification',
            name='authority_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanction_notifications_authority_2', to=settings.AUTH_USER_MODEL, verbose_name='Firma 2'),
        ),
    ]
