# Generated by Django 6.0 on 2026-05-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0012_alter_sanctionnotification_authority_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionnotification',
            name='has_responded',
            field=models.BooleanField(default=False, verbose_name='¿Ha respondido?'),
        ),
        migrations.AddField(
            model_name='sanctionnotification',
            name='status',
            field=models.CharField(choices=[('GENERADO', 'Generado'), ('EN_PROCESO', 'En proceso'), ('ARCHIVADO', 'Archivado'), ('SANCIONADO', 'Sancionado')], default='GENERADO', max_length=20, verbose_name='Estado'),
        ),
    ]
