# Generated by Django 6.0 on 2026-05-08 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0013_sanctionnotification_has_responded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Despacho')),
                ('is_current', models.BooleanField(default=True, verbose_name='¿Es la asignación activa?')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Instrucciones/Observaciones')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_sanction_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_sanction_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Actual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='sanctions.sanctionnotification', verbose_name='Notificación Relacionada')),
                ('sanction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='sanctions.sanction', verbose_name='Sanción Resultante')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Asignación de Sanción',
                'verbose_name_plural': 'Asignaciones de Sanciones',
                'ordering': ['created_at'],
            },
        ),
    ]
