# Generated by Django 6.0 on 2026-05-08 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0014_sanctionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctiontype',
            name='authority_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_types_auth1', to=settings.AUTH_USER_MODEL, verbose_name='Primera Autoridad'),
        ),
        migrations.AddField(
            model_name='sanctiontype',
            name='authority_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_types_auth2', to=settings.AUTH_USER_MODEL, verbose_name='Segunda Autoridad'),
        ),
        migrations.AddField(
            model_name='sanctiontype',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_types_register', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='sanctiontype',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_types_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
