# Generated by Django 6.0 on 2026-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0015_sanctiontype_authority_1_sanctiontype_authority_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la falta'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='incident_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del incidente'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='sanction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la sanción'),
        ),
    ]
