# Generated by Django 6.0 on 2026-05-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0016_alter_sanction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionnotification',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='¿Fue notificado?'),
        ),
        migrations.AddField(
            model_name='sanctionnotification',
            name='notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de notificación'),
        ),
        migrations.AlterField(
            model_name='sanctionnotification',
            name='status',
            field=models.CharField(choices=[('GENERADO', 'Generado'), ('NOTIFICADO', 'Notificado'), ('EN_PROCESO', 'En proceso'), ('ARCHIVADO', 'Archivado'), ('SANCIONADO', 'Sancionado')], default='GENERADO', max_length=20, verbose_name='Estado'),
        ),
    ]
