# Generated by Django 6.0 on 2026-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0018_sanctionnotification_days_without_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionnotificationtypemapping',
            name='source_key',
            field=models.CharField(choices=[('employee_full_name', 'Nombre completo del empleado'), ('employee_first_name', 'Nombres del empleado'), ('employee_last_name', 'Apellidos del empleado'), ('employee_document_number', 'Documento del empleado'), ('employee_position', 'Cargo del empleado'), ('employee_unit', 'Unidad / área del empleado'), ('regime_code', 'Código del régimen'), ('regime_name', 'Nombre del régimen'), ('notification_name', 'Nombre del tipo de notificación'), ('month_name', 'Nombre del mes'), ('month_number', 'Número del mes'), ('year', 'Año'), ('registration_date', 'Fecha de registro'), ('authority_1_name', 'Nombre de la autoridad 1'), ('authority_1_position', 'Cargo de la autoridad 1'), ('authority_2_name', 'Nombre de la autoridad 2'), ('authority_2_position', 'Cargo de la autoridad 2'), ('minutes_late', 'Minutos de atraso'), ('regs_without_mark', 'Registros sin marcar'), ('days_without_mark', 'Dias sin marcar'), ('observations', 'Observaciones')], max_length=60, verbose_name='Fuente de datos'),
        ),
    ]
