# Generated by Django 6.0 on 2026-06-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0019_alter_sanctionnotificationtypemapping_source_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionnotification',
            name='elaborated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notif_elaborator', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por'),
        ),
        migrations.AddField(
            model_name='sanctionnotification',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notif_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.DeleteModel(
            name='SanctionNotificationTypeMapping',
        ),
    ]
