# Generated by Django 6.0 on 2026-01-26 09:26

from django.db import migrations


def convert_all_timestamps_to_naive(apps, schema_editor):
    """
    Convierte TODOS los campos timestamp with time zone del esquema public
    a timestamp without time zone de forma automática.
    """
    with schema_editor.connection.cursor() as cursor:
        # Obtener todas las columnas timestamp with time zone
        cursor.execute("""
            SELECT table_name, column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' 
            AND data_type = 'timestamp with time zone'
            ORDER BY table_name, column_name;
        """)
        
        columns = cursor.fetchall()
        
        for table_name, column_name in columns:
            try:
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    ALTER COLUMN {column_name} TYPE timestamp without time zone;
                """)
                print(f"✓ Convertido {table_name}.{column_name}")
            except Exception as e:
                print(f"✗ Error en {table_name}.{column_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authorities'),
    ]

    operations = [
        migrations.RunPython(convert_all_timestamps_to_naive, reverse_code=migrations.RunPython.noop),
    ]
