# Generated by Django 6.0 on 2026-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_custom_signature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='sanction_green_days',
            field=models.PositiveIntegerField(default=2, help_text='Hasta cuántos días el trámite se considera a tiempo.', verbose_name='Días para Semáforo Verde'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='sanction_yellow_days',
            field=models.PositiveIntegerField(default=5, help_text='Hasta cuántos días el trámite está en alerta.', verbose_name='Días para Semáforo Amarillo'),
        ),
    ]
