# Generated by Django 6.0 on 2026-06-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemconfiguration_sanction_green_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authority',
        ),
    ]
