# Generated by Django 6.0 on 2026-03-20 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden de Reporte'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order',), name='unique_active_account_order'),
        ),
    ]
