# Generated by Django 6.0 on 2026-02-12 17:49

import datetime
import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_code', models.CharField(help_text='Identificador único del documento', max_length=50, unique=True, verbose_name='Nro. Archivo/Radicado')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remitente / Responsable')),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirigido a')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=documents.models.Document.document_upload_path, verbose_name='Archivo Digital')),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='Tipo de Registro')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-registration_date'],
            },
        ),
    ]
