# Generated by Django 6.0 on 2026-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirigido a'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remitente / Responsable'),
        ),
    ]
