# Generated by Django 6.0 on 2025-12-22 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Nivel')),
                ('level_order', models.PositiveIntegerField(help_text='1 para la cabeza (Institución), números mayores para dependencias.', verbose_name='Orden Jerárquico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Nivel Organizacional',
                'verbose_name_plural': 'Niveles Organizacionales',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Unidad')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC (Opcional)')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno/Partida')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación Física')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Extensión')),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to='employee.employee', verbose_name='Jefe Inmediato / Responsable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='institution.administrativeunit', verbose_name='Pertenece a (Padre)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='institution.organizationallevel', verbose_name='Nivel Jerárquico')),
            ],
            options={
                'verbose_name': 'Unidad Administrativa',
                'verbose_name_plural': 'Unidades Administrativas',
                'ordering': ['level__level_order', 'name'],
            },
        ),
    ]
