# Generated by Django 6.0 on 2026-01-26 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Entregable')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción/Especificaciones')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frecuencia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='institution.administrativeunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['name'],
            },
        ),
    ]
