# Generated by Django 6.0 on 2026-01-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_deliverable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='frequency',
        ),
    ]
