# Generated by Django 6.0 on 2026-01-29 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_remove_deliverable_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeunit',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Unidad Administrativa', 'verbose_name_plural': 'Unidades Administrativas'},
        ),
        migrations.CreateModel(
            name='InstitutionOrganigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='institution/organigram/', verbose_name='Imagen del Organigrama')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Organigrama Posicional',
                'verbose_name_plural': 'Organigramas',
            },
        ),
    ]
