# Generated by Django 6.0 on 2026-10-07 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_institutionaldata_original_budget_line'),
        ('institution', '0004_alter_administrativeunit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionorganigram',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Organigrama Posicional', 'verbose_name_plural': 'Organigramas'},
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código Interno / Partida Presupuestaria'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombre de la Unidad'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='institution.administrativeunit', verbose_name='Pertenece a (Unidad Padre)'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono / Extensión'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción / Especificaciones Requeridas'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='institution.administrativeunit', verbose_name='Unidad Administrativa'),
        ),
        migrations.AlterField(
            model_name='institutionorganigram',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AlterField(
            model_name='institutionorganigram',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='organizationallevel',
            name='level_order',
            field=models.PositiveIntegerField(db_index=True, help_text='1 para el nivel superior (ej. Alcaldía), números mayores para dependencias subordinadas.', verbose_name='Orden Jerárquico'),
        ),
        migrations.AlterField(
            model_name='organizationallevel',
            name='name',
            field=models.CharField(error_messages={'unique': 'Ya existe un nivel jerárquico con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre del Nivel'),
        ),
        migrations.AddIndex(
            model_name='administrativeunit',
            index=models.Index(fields=['parent', 'is_active'], name='idx_unit_parent_active'),
        ),
        migrations.AddIndex(
            model_name='administrativeunit',
            index=models.Index(fields=['boss', 'is_active'], name='idx_unit_boss_active'),
        ),
        migrations.AddIndex(
            model_name='administrativeunit',
            index=models.Index(fields=['code', 'is_active'], name='idx_unit_code_active'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['unit', 'is_active'], name='idx_deliverable_unit_active'),
        ),
        migrations.AddIndex(
            model_name='organizationallevel',
            index=models.Index(fields=['level_order', 'is_active'], name='idx_orglevel_order_active'),
        ),
    ]
