# Generated by Django 6.0 on 2026-01-08 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Horario')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('morning_start', models.TimeField(verbose_name='Inicio (Jornada 1)')),
                ('morning_end', models.TimeField(verbose_name='Fin (Jornada 1)')),
                ('morning_crosses_midnight', models.BooleanField(default=False, verbose_name='Cruza medianoche (J1)')),
                ('afternoon_start', models.TimeField(blank=True, null=True, verbose_name='Inicio (Jornada 2)')),
                ('afternoon_end', models.TimeField(blank=True, null=True, verbose_name='Fin (Jornada 2)')),
                ('afternoon_crosses_midnight', models.BooleanField(default=False, verbose_name='Cruza medianoche (J2)')),
                ('monday', models.BooleanField(default=True, verbose_name='Lun')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Mar')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Mié')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jue')),
                ('friday', models.BooleanField(default=True, verbose_name='Vie')),
                ('saturday', models.BooleanField(default=False, verbose_name='Sáb')),
                ('sunday', models.BooleanField(default=False, verbose_name='Dom')),
                ('late_tolerance_minutes', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tolerancia (min)')),
                ('daily_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas Diarias')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'schedule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('is_current', models.BooleanField(default=True, verbose_name='Actual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_history', to='employee.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Asignación de Horario',
                'db_table': 'employee_schedule_history',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detalle/Descripción')),
                ('start_date', models.DateField(verbose_name='Desde')),
                ('end_date', models.DateField(verbose_name='Hasta')),
                ('is_holiday', models.BooleanField(default=True, verbose_name='Es Feriado')),
                ('applies_to_all', models.BooleanField(default=True, verbose_name='Aplica a Todos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Feriado/Observación',
                'verbose_name_plural': 'Feriados y Observaciones',
                'db_table': 'schedule_observation',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleObservationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_employees', to='schedule.scheduleobservation')),
            ],
            options={
                'db_table': 'schedule_observation_employee',
                'unique_together': {('observation', 'employee')},
            },
        ),
    ]
