# Generated by Django 6.0 on 2026-01-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleObservationEmployee',
        ),
    ]
