# Generated by Django 6.0 on 2026-01-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_delete_scheduleobservationemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleobservation',
            name='applies_to_all',
        ),
    ]
