# Generated by Django 6.0 on 2026-04-28 08:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_scheduleobservation_applies_to_all'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('effective_from', models.DateField(verbose_name='Vigente Desde')),
                ('morning_start', models.TimeField(verbose_name='Inicio (Jornada 1)')),
                ('morning_end', models.TimeField(verbose_name='Fin (Jornada 1)')),
                ('morning_crosses_midnight', models.BooleanField(default=False, verbose_name='Cruza medianoche (J1)')),
                ('afternoon_start', models.TimeField(blank=True, null=True, verbose_name='Inicio (Jornada 2)')),
                ('afternoon_end', models.TimeField(blank=True, null=True, verbose_name='Fin (Jornada 2)')),
                ('afternoon_crosses_midnight', models.BooleanField(default=False, verbose_name='Cruza medianoche (J2)')),
                ('monday', models.BooleanField(default=True, verbose_name='Lun')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Mar')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Mié')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jue')),
                ('friday', models.BooleanField(default=True, verbose_name='Vie')),
                ('saturday', models.BooleanField(default=False, verbose_name='Sáb')),
                ('sunday', models.BooleanField(default=False, verbose_name='Dom')),
                ('late_tolerance_minutes', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tolerancia (min)')),
                ('daily_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas Diarias')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo del Cambio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='schedule.schedule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Horario',
                'verbose_name_plural': 'Historial de Cambios de Horarios',
                'db_table': 'schedule_change_history',
                'ordering': ['-effective_from'],
            },
        ),
    ]
