# Generated by Django 6.0 on 2026-01-09 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0002_alter_activity_is_active_alter_program_is_active_and_more'),
        ('core', '0001_initial'),
        ('employee', '0002_initial'),
        ('institution', '0001_initial'),
        ('schedule', '0003_remove_scheduleobservation_applies_to_all'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Régimen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Régimen Laboral',
                'verbose_name_plural': 'Regímenes Laborales',
                'db_table': 'labor_regime',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Tipo de Contrato')),
                ('contract_type_category', models.CharField(choices=[('CONTRATO', 'Contrato'), ('ACCION_PERSONAL', 'Acción de Personal')], default='CONTRATO', max_length=20, verbose_name='Categoría de Documento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('labor_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_types', to='contract.laborregime', verbose_name='Régimen Laboral')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'db_table': 'contract_type',
                'ordering': ['name'],
                'unique_together': {('labor_regime', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ManagementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('document_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Número de Documento')),
                ('job_functions', models.TextField(verbose_name='Funciones del Puesto')),
                ('workplace', models.CharField(max_length=255, verbose_name='Lugar de Trabajo')),
                ('institutional_need_memo', models.CharField(max_length=100, verbose_name='Memo Necesidad')),
                ('budget_certification', models.CharField(max_length=100, verbose_name='Certificación Presup.')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Documento Firmado')),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='institution.administrativeunit', verbose_name='Unidad Administrativa')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='budget.budgetline', verbose_name='Partida Presupuestaria')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='contract.contracttype', verbose_name='Tipo de Contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='employee.employee', verbose_name='Empleado')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='schedule.schedule', verbose_name='Horario')),
                ('status', models.ForeignKey(limit_choices_to={'catalog__code': 'CONTRACT_STATUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='periods_by_status', to='core.catalogitem', verbose_name='Estado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Período de Gestión',
                'verbose_name_plural': 'Períodos de Gestión',
                'db_table': 'management_period',
                'ordering': ['-start_date'],
            },
        ),
    ]
