# Generated by Django 6.0 on 2026-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborregime',
            options={'ordering': ['-code'], 'verbose_name': 'Régimen Laboral', 'verbose_name_plural': 'Regímenes Laborales'},
        ),
        migrations.AlterField(
            model_name='managementperiod',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Número de Documento'),
        ),
    ]
