# Generated by Django 6.0 on 2026-03-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_laborregime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='historical_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo en ese momento'),
        ),
        migrations.AddField(
            model_name='history',
            name='historical_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sueldo en ese momento'),
        ),
    ]
