# Generated by Django 6.0 on 2026-03-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetgroup_budgetline_budget_group'),
        ('contract', '0003_history_historical_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementperiod',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetline'),
        ),
    ]
