# Generated by Django 6.0 on 2026-04-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_managementperiod_budget_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementperiod',
            options={'ordering': ['-created_at'], 'verbose_name': 'Período de Gestión', 'verbose_name_plural': 'Períodos de Gestión'},
        ),
    ]
