# Generated by Django 6.0 on 2026-04-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_managementperiod_manual_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('contract_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_template', to='contract.contracttype', verbose_name='Modalidad de contratación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Plantilla de contrato',
                'verbose_name_plural': 'Plantillas de contrato',
                'ordering': ['contract_type__labor_regime__code', 'contract_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('section_type', models.CharField(choices=[('PARAGRAPH', 'Párrafo (justificado)'), ('TITLE', 'Título (izquierda)')], default='PARAGRAPH', max_length=20, verbose_name='Tipo de sección')),
                ('content', models.TextField(help_text='Puede incluir variables: [FULL_NAME], [DOCUMENT_NUMBER], [START_DATE], etc.', verbose_name='Contenido')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='contract.contracttemplate', verbose_name='Plantilla')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Sección de plantilla contractual',
                'verbose_name_plural': 'Secciones de plantillas contractuales',
                'ordering': ['template', 'order'],
            },
        ),
    ]
