# Generated by Django 6.0 on 2026-04-10 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_contracttemplate_contracttemplatesection'),
        ('institution', '0004_alter_administrativeunit_options_and_more'),
        ('schedule', '0003_remove_scheduleobservation_applies_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementperiod',
            name='action_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explicación de Acción'),
        ),
        migrations.AddField(
            model_name='managementperiod',
            name='action_motivation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivación de Acción'),
        ),
        migrations.AddField(
            model_name='managementperiod',
            name='elaboration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elaboración'),
        ),
        migrations.AlterField(
            model_name='managementperiod',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='institution.administrativeunit', verbose_name='Unidad Administrativa'),
        ),
        migrations.AlterField(
            model_name='managementperiod',
            name='budget_certification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificación Presup.'),
        ),
        migrations.AlterField(
            model_name='managementperiod',
            name='institutional_need_memo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Memo Necesidad'),
        ),
        migrations.AlterField(
            model_name='managementperiod',
            name='job_functions',
            field=models.TextField(blank=True, null=True, verbose_name='Funciones del Puesto'),
        ),
        migrations.AlterField(
            model_name='managementperiod',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='schedule.schedule', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='managementperiod',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de Trabajo'),
        ),
    ]
