# Generated by Django 6.0 on 2026-04-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_managementperiod_action_explanation_and_more'),
        ('personnel_actions', '0003_alter_personnelaction_authority_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementperiod',
            name='personnel_action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_period', to='personnel_actions.personnelaction', verbose_name='Acción de personal vinculada'),
        ),
    ]
