# Generated by Django 6.0 on 2026-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_managementperiod_personnel_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='history',
            name='type',
        ),
        migrations.AddField(
            model_name='history',
            name='historical_administrative_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidad administrativa en ese momento'),
        ),
    ]
