# Generated by Django 6.0 on 2026-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_remove_history_reason_remove_history_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
    ]
