# Generated by Django 6.0 on 2026-06-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_history_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='historical_administrative_unit',
        ),
    ]
