# Generated by Django 6.0 on 2026-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_remove_history_historical_administrative_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Movimiento'),
        ),
    ]
