# Generated by Django 6.0 on 2026-02-10 08:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_payrollinfo_roles_count'),
        ('permitrequest', '0002_permitrequest_response_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True, verbose_name='Nombre Periodo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado Periodo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeVacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Días')),
                ('balance_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Saldo Días')),
                ('taken_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días Tomados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Empleado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacation.vacationperiod', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Saldo Vacacional',
                'verbose_name_plural': 'Saldos Vacacionales',
                'ordering': ['-pk'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha Desde')),
                ('end_date', models.DateField(verbose_name='Fecha Hasta')),
                ('date_issued', models.DateField(default=datetime.date.today, verbose_name='Fecha Emisión')),
                ('days_quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Días Solicitados')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Explicación/Motivo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacation_approver', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('balance_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vacation.employeevacationbalance', verbose_name='Periodo Afectado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacation_creator', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacación',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='VacationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='Tipo Acción')),
                ('days_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor en Días')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('permit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='permitrequest.permitrequest', verbose_name='Permiso Relacionado')),
                ('vacation_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacation.employeevacationbalance', verbose_name='Saldo Afectado')),
                ('vacation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vacation.vacationrequest', verbose_name='Solicitud Vacación')),
            ],
            options={
                'verbose_name': 'Historial Vacación',
                'verbose_name_plural': 'Historiales Vacaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
