# Generated by Django 6.0 on 2026-02-10 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_actions', '0001_initial'),
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='personnel_action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacation_request', to='personnel_actions.personnelaction', verbose_name='Acción de Personal'),
        ),
    ]
