# Generated by Django 6.0 on 2026-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_vacationrequest_personnel_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevacationbalance',
            name='observation',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
    ]
