# Generated by Django 6.0 on 2026-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_employeevacationbalance_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevacationbalance',
            name='additional_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días Adicionales (Balance Anterior)'),
        ),
        migrations.AddField(
            model_name='employeevacationbalance',
            name='permit_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días de Permisos con Cargo'),
        ),
        migrations.AddField(
            model_name='employeevacationbalance',
            name='vacation_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días de Liquidación Vacaciones'),
        ),
    ]
