# Generated by Django 6.0 on 2026-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0004_employeevacationbalance_additional_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationhistory',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='vacationhistory',
            name='days_value',
        ),
        migrations.AddField(
            model_name='vacationhistory',
            name='days_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Dias Descuento'),
        ),
        migrations.AddField(
            model_name='vacationhistory',
            name='hours_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Descuento'),
        ),
        migrations.AddField(
            model_name='vacationhistory',
            name='minutes_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Minutos Descuento'),
        ),
        migrations.AddField(
            model_name='vacationhistory',
            name='proportional_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento Proporcional'),
        ),
        migrations.AddField(
            model_name='vacationhistory',
            name='value_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Descuento'),
        ),
    ]
