# Generated by Django 6.0 on 2026-02-05 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_payrollinfo_roles_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de permiso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('needs_justification', models.BooleanField(default=True, verbose_name='¿Necesita justificar?')),
                ('affects_vacation', models.BooleanField(default=False, verbose_name='¿Descuento a vacaciones?')),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='¿Adjuntar PDF?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='permitrequest.permittype', verbose_name='Dependiente de')),
            ],
            options={
                'verbose_name': 'Tipo de permiso',
                'verbose_name_plural': 'Tipos de permiso',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('days', models.IntegerField(default=0, verbose_name='Días')),
                ('hours', models.IntegerField(default=0, verbose_name='Horas')),
                ('minutes', models.IntegerField(default=0, verbose_name='Minutos')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('CANCELED', 'Anulado')], default='REQUESTED', max_length=20, verbose_name='Estado')),
                ('justification_file', models.FileField(blank=True, null=True, upload_to='documents/permits/%Y/%m/', verbose_name='Justificativo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='employee.employee', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('permit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permitrequest.permittype', verbose_name='Tipo de Permiso')),
            ],
            options={
                'verbose_name': 'Solicitud de Permiso',
                'verbose_name_plural': 'Solicitudes de Permisos',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'status'], name='permitreque_employe_d9bdb3_idx'), models.Index(fields=['start_date'], name='permitreque_start_d_15251d_idx')],
            },
        ),
    ]
