# Generated by Django 6.0 on 2026-04-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permitrequest', '0002_permitrequest_response_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequest',
            options={'ordering': ['-start_date'], 'permissions': [('can_edit', 'Puede editar y revisar bitácoras de permisos'), ('can_admin', 'Puede administrar Permisos y Bitácoras')], 'verbose_name': 'Solicitud de Permiso', 'verbose_name_plural': 'Solicitudes de Permisos'},
        ),
    ]
