# Generated by Django 6.0 on 2025-12-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('is_boss', models.BooleanField(default=False, help_text='Marcar si esta persona es la máxima autoridad de la unidad asignada.', verbose_name='Es Jefe/Director de Área')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('date_left', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['person__last_name'],
            },
        ),
    ]
