# Generated by Django 6.0 on 2026-01-13 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employee', '0002_initial'),
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_boss',
            field=models.BooleanField(default=False, verbose_name='Es Jefe/Director de Área'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='curriculum/pdfs/', verbose_name='Curriculum PDF')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='person.person', verbose_name='Persona')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
            },
        ),
        migrations.CreateModel(
            name='AcademicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('title_obtained', models.CharField(max_length=200, verbose_name='Título Obtenido')),
                ('educational_institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('senescyt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° SENESCYT')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Año de Graduación')),
                ('is_current', models.BooleanField(default=False, verbose_name='En Curso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('education_level', models.ForeignKey(limit_choices_to={'catalog__code': 'EDUCATION_LEVELS'}, on_delete=django.db.models.deletion.PROTECT, related_name='academic_titles_by_level', to='core.catalogitem', verbose_name='Nivel de Instrucción')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_titles', to='employee.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economic_data', to='person.person', verbose_name='Persona')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Datos Económicos',
                'verbose_name_plural': 'Datos Económicos',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('holder_name', models.CharField(max_length=200, verbose_name='Titular')),
                ('account_type', models.ForeignKey(limit_choices_to={'catalog__code': 'ACCOUNT_TYPES'}, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_as_type', to='core.catalogitem', verbose_name='Tipo de Cuenta')),
                ('bank', models.ForeignKey(limit_choices_to={'catalog__code': 'BANCO'}, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_as_bank', to='core.catalogitem', verbose_name='Banco')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('economic_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='employee.economicdata')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('file_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Expediente')),
                ('biometric_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Biométrico')),
                ('institutional_email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo Institucional')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_data', to='employee.employee', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Datos Institucionales',
                'verbose_name_plural': 'Datos Institucionales',
            },
        ),
        migrations.CreateModel(
            name='PayrollInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('monthly_payment', models.BooleanField(default=False, verbose_name='Mensualiza Décimos')),
                ('reserve_funds', models.BooleanField(default=False, verbose_name='Mensualiza Fondos Reserva')),
                ('family_dependents', models.IntegerField(default=0, verbose_name='Cargas Familiares')),
                ('education_dependents', models.IntegerField(default=0, verbose_name='Cargas Educación')),
                ('roles_entry_date', models.DateField(blank=True, null=True, verbose_name='Ingreso a Roles')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('economic_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_info', to='employee.economicdata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('training_name', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('hours', models.IntegerField(verbose_name='Horas')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='employee.curriculum')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('company_name', models.CharField(max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Trabajo Actual')),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='employee.curriculum')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
