# Generated by Django 6.0 on 2026-01-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_is_boss_curriculum_academictitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academictitle',
            options={'verbose_name': 'Título Académico', 'verbose_name_plural': 'Títulos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='payrollinfo',
            options={'verbose_name': 'Información de Nómina', 'verbose_name_plural': 'Información de Nómina'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Capacitación', 'verbose_name_plural': 'Capacitaciones'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencias Laborales'},
        ),
    ]
