# Generated by Django 6.0 on 2026-01-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_academictitle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinfo',
            name='roles_count',
            field=models.IntegerField(default=0, verbose_name='Número de Roles'),
        ),
    ]
