# Generated by Django 6.0 on 2026-02-18 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_payrollinfo_roles_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionaldata',
            name='collective_contract',
            field=models.BooleanField(default=False, verbose_name='Es contrato colectivo'),
        ),
        migrations.AddField(
            model_name='institutionaldata',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
    ]
