# Generated by Django 6.0 on 2026-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_institutionaldata_collective_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionaldata',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
