# Generated by Django 6.0 on 2026-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_institutionaldata_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollinfo',
            name='education_dependents',
            field=models.IntegerField(default=0, verbose_name='Hijos con discapacidad'),
        ),
        migrations.AlterField(
            model_name='payrollinfo',
            name='family_dependents',
            field=models.IntegerField(default=0, verbose_name='Hijos dependientes'),
        ),
    ]
