# Generated by Django 6.0 on 2026-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_teleworkactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinfo',
            name='immediate_reserve_funds',
            field=models.BooleanField(default=False, help_text='Marcar si el empleado certifica continuidad en el sector público (no requiere esperar 1 año)', verbose_name='Derecho a Fondos de Reserva Inmediato'),
        ),
    ]
