# Generated by Django 6.0 on 2026-06-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_payrollinfo_immediate_reserve_funds'),
        ('institution', '0004_alter_administrativeunit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionaldata',
            name='original_dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutional_data_original', to='institution.administrativeunit', verbose_name='Dependencia Original'),
        ),
        migrations.AddField(
            model_name='institutionaldata',
            name='original_dependency_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Dependencia Original'),
        ),
    ]
