# Generated by Django 6.0 on 2026-10-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budgetassignmenthistory_is_acting'),
        ('employee', '0012_institutionaldata_original_dependency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionaldata',
            name='original_budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutional_original_employees', to='budget.budgetline', verbose_name='Partida Presupuestaria Original / Titular'),
        ),
    ]
