# Generated by Django 6.0 on 2026-01-21 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_payrollinfo_roles_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nombre del Dispositivo')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='Puerto')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('location', models.CharField(max_length=250, verbose_name='Ubicación Física')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Biométrico',
                'verbose_name_plural': 'Biométricos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('num_records', models.IntegerField(default=0, verbose_name='Registros Cargados')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo/Observación')),
                ('load_type', models.CharField(default='AUTOMATIC', max_length=50, verbose_name='Tipo de Carga')),
                ('biometric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='biometric.biometricdevice', verbose_name='Biométrico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Carga de Biométrico',
                'verbose_name_plural': 'Cargas de Biométricos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('employee_id_bio', models.CharField(max_length=20, verbose_name='ID en Biométrico')),
                ('registry_date', models.DateTimeField(verbose_name='Fecha/Hora de Marcación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employee.employee', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('biometric_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biometric.biometricload')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-registry_date'],
            },
        ),
    ]
