# Generated by Django 6.0 on 2026-01-26 09:26

from django.db import migrations


def convert_to_naive_timestamps(apps, schema_editor):
    """
    Convierte todos los campos timestamp with time zone a timestamp without time zone
    y ajusta los datos existentes para mantener la hora local sin offset.
    """
    db_alias = schema_editor.connection.alias
    
    # Ejecutar SQL directo para cambiar el tipo de columna
    with schema_editor.connection.cursor() as cursor:
        # Para BiometricDevice
        cursor.execute("""
            ALTER TABLE biometric_biometricdevice 
            ALTER COLUMN created_at TYPE timestamp without time zone;
        """)
        cursor.execute("""
            ALTER TABLE biometric_biometricdevice 
            ALTER COLUMN updated_at TYPE timestamp without time zone;
        """)
        
        # Para BiometricLoad
        cursor.execute("""
            ALTER TABLE biometric_biometricload 
            ALTER COLUMN created_at TYPE timestamp without time zone;
        """)
        cursor.execute("""
            ALTER TABLE biometric_biometricload 
            ALTER COLUMN updated_at TYPE timestamp without time zone;
        """)
        
        # Para AttendanceRegistry
        cursor.execute("""
            ALTER TABLE biometric_attendanceregistry 
            ALTER COLUMN created_at TYPE timestamp without time zone;
        """)
        cursor.execute("""
            ALTER TABLE biometric_attendanceregistry 
            ALTER COLUMN updated_at TYPE timestamp without time zone;
        """)
        cursor.execute("""
            ALTER TABLE biometric_attendanceregistry 
            ALTER COLUMN registry_date TYPE timestamp without time zone;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_to_naive_timestamps, reverse_code=migrations.RunPython.noop),
    ]
