# Generated by Django 6.0 on 2026-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0003_biometriccommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
    ]
