# Generated by Django 6.0 on 2026-04-13 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0005_offlineattendanceregistry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='offlineattendanceregistry',
            new_name='biometric_o_sync_st_b06b15_idx',
            old_name='bio_offline_sync_captured_idx',
        ),
        migrations.RenameIndex(
            model_name='offlineattendanceregistry',
            new_name='biometric_o_employe_1af678_idx',
            old_name='bio_offline_employee_captured_idx',
        ),
        migrations.AddField(
            model_name='offlineattendanceregistry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='offlineattendanceregistry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
