# Generated by Django 6.0 on 2026-02-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_payrollinfo_roles_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('type', models.CharField(choices=[('Mensual', 'Monthly'), ('Quincenal', 'Bi-weekly')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Constante de Nómina',
                'verbose_name_plural': 'Constantes de Nómina',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=15, verbose_name='Mes')),
                ('year', models.CharField(max_length=4, verbose_name='Año')),
                ('working_days', models.IntegerField(default=30)),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
            ],
            options={
                'ordering': ['-year', '-id'],
                'indexes': [models.Index(fields=['year', 'month'], name='payroll_pay_year_149b61_idx')],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_days', models.IntegerField(default=30)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employee.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['employee__pk'],
            },
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('DEDUCTION', 'Descuento')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deduction_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.deduction')),
                ('income_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.income')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payslip')),
            ],
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['period', 'employee'], name='payroll_pay_period__66dc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipitem',
            index=models.Index(fields=['payslip', 'item_type'], name='payroll_pay_payslip_721e7b_idx'),
        ),
    ]
