# Generated by Django 6.0 on 2026-02-04 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Inicio'),
            preserve_default=False,
        ),
    ]
