# Generated by Django 6.0 on 2026-02-04 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollperiod_end_date_payrollperiod_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-year', '-id'], 'verbose_name': 'Periodo de Nómina'},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name': 'Rol de Pago'},
        ),
        migrations.RemoveIndex(
            model_name='payrollperiod',
            name='payroll_pay_year_149b61_idx',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payslip',
            name='extra_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Extras (Fines de semana)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Nocturnas'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='supplementary_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Suplementarias (Lun-Vie)'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='working_days',
            field=models.IntegerField(default=30, verbose_name='Días Laborables'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='worked_days',
            field=models.IntegerField(default=30, verbose_name='Días Trabajados'),
        ),
    ]
