# Generated by Django 6.0 on 2026-03-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('budget', '0002_alter_activity_is_active_alter_program_is_active_and_more'),
        ('payroll', '0003_alter_payrollperiod_options_alter_payslip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to='accounting.account', verbose_name='Cuenta Contable'),
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='accounting.account', verbose_name='Cuenta Contable'),
        ),
        migrations.AddField(
            model_name='payslipitem',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_items', to='budget.budgetline', verbose_name='Partida Presupuestaria'),
        ),
    ]
