# Generated by Django 6.0 on 2026-03-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_activity_is_active_alter_program_is_active_and_more'),
        ('institution', '0004_alter_administrativeunit_options_and_more'),
        ('payroll', '0004_deduction_account_income_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroBudgetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('DEDUCTION', 'Descuento')], max_length=10)),
                ('rubro_code', models.CharField(max_length=50, verbose_name='Código Rubro')),
                ('is_active', models.BooleanField(default=True)),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubro_mappings', to='institution.administrativeunit', verbose_name='Unidad Administrativa (opcional)')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubro_mappings', to='budget.budgetline')),
            ],
            options={
                'verbose_name': 'Mapa Rubro-Partida',
                'verbose_name_plural': 'Mapas Rubro-Partida',
                'unique_together': {('rubro_type', 'rubro_code', 'administrative_unit')},
            },
        ),
    ]
