# Generated by Django 6.0 on 2026-03-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('payroll', '0005_rubrobudgetmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.AddField(
            model_name='deduction',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_credits', to='accounting.account', verbose_name='Cuenta HABER (Retención a Pagar)'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_debits', to='accounting.account', verbose_name='Cuenta DEBE (Reducción Pasivo)'),
        ),
        migrations.AddField(
            model_name='income',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_credits', to='accounting.account', verbose_name='Cuenta HABER (Pasivo/Pago)'),
        ),
        migrations.AddField(
            model_name='income',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_debits', to='accounting.account', verbose_name='Cuenta DEBE (Gasto)'),
        ),
    ]
