# Generated by Django 6.0 on 2026-03-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_remove_deduction_account_remove_income_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrobudgetmapping',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='Activar para partidas únicas (ej. Subrogación). Desactivar para solo reemplazar el ítem de gasto al final (ej. Fondos de Reserva).', verbose_name='¿Es Partida Fija?'),
        ),
    ]
