# Generated by Django 6.0 on 2026-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_rubrobudgetmapping_is_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipitem',
            name='budget_line_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Partida Aplicada (Histórico)'),
        ),
    ]
