# Generated by Django 6.0 on 2026-03-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_activity_is_active_alter_program_is_active_and_more'),
        ('payroll', '0008_payslipitem_budget_line_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrobudgetmapping',
            name='dynamic_suffix',
            field=models.CharField(blank=True, help_text='Ej: "5.1.06.02" o "06.02". Reemplazará la parte final de la partida del empleado.', max_length=50, null=True, verbose_name='Sufijo Dinámico (Ítem de Gasto)'),
        ),
        migrations.AlterField(
            model_name='rubrobudgetmapping',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubro_mappings', to='budget.budgetline', verbose_name='Partida Fija'),
        ),
    ]
