# Generated by Django 6.0 on 2026-03-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_rubrobudgetmapping_dynamic_suffix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrobudgetmapping',
            options={'verbose_name': 'Mapa Rubro-Partida'},
        ),
        migrations.AlterUniqueTogether(
            name='rubrobudgetmapping',
            unique_together={('rubro_type', 'rubro_code')},
        ),
        migrations.RemoveField(
            model_name='rubrobudgetmapping',
            name='administrative_unit',
        ),
        migrations.RemoveField(
            model_name='rubrobudgetmapping',
            name='budget_line',
        ),
    ]
