# Generated by Django 6.0 on 2026-03-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_rubrobudgetmapping_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='type',
        ),
    ]
