# Generated by Django 6.0 on 2026-03-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_institutionaldata_entry_date'),
        ('payroll', '0011_remove_deduction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor ($)')),
                ('deduction_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction', verbose_name='Rubro de Egreso')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='employee.employee', verbose_name='Empleado')),
                ('income_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.income', verbose_name='Rubro de Ingreso')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='payroll.payrollperiod', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Novedad de Nómina',
                'verbose_name_plural': 'Novedades de Nómina',
                'unique_together': {('period', 'employee', 'deduction_ref'), ('period', 'employee', 'income_ref')},
            },
        ),
    ]
