# Generated by Django 6.0 on 2026-03-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('payroll', '0012_payrollnovelty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrobudgetmapping',
            options={'verbose_name': 'Mapeo Presupuestario', 'verbose_name_plural': 'Mapeos Presupuestarios'},
        ),
        migrations.AlterUniqueTogether(
            name='rubrobudgetmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rubrobudgetmapping',
            name='deduction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_mapping', to='payroll.deduction', verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='rubrobudgetmapping',
            name='income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_mapping', to='payroll.income', verbose_name='Ingreso'),
        ),
        migrations.AlterField(
            model_name='rubrobudgetmapping',
            name='dynamic_suffix',
            field=models.CharField(help_text='Ej: 5.1.01.05', max_length=50, verbose_name='Sufijo Presupuestario'),
        ),
        migrations.AlterField(
            model_name='rubrobudgetmapping',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='¿Es partida fija?'),
        ),
        migrations.CreateModel(
            name='InstitutionalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Aporte')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del Algoritmo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrib_credits', to='accounting.account', verbose_name='Cuenta HABER (Pasivo)')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrib_debits', to='accounting.account', verbose_name='Cuenta DEBE (Gasto)')),
            ],
            options={
                'verbose_name': 'Aporte Institucional',
                'verbose_name_plural': 'Aportes Institucionales',
            },
        ),
        migrations.AddField(
            model_name='rubrobudgetmapping',
            name='contribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_mapping', to='payroll.institutionalcontribution', verbose_name='Aporte Institucional'),
        ),
        migrations.RemoveField(
            model_name='rubrobudgetmapping',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rubrobudgetmapping',
            name='rubro_code',
        ),
        migrations.RemoveField(
            model_name='rubrobudgetmapping',
            name='rubro_type',
        ),
    ]
