# Generated by Django 6.0 on 2026-03-11 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_rubrobudgetmapping_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipitem',
            name='contribution_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.institutionalcontribution'),
        ),
    ]
