# Generated by Django 6.0 on 2026-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_payslipitem_contribution_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipitem',
            name='item_type',
            field=models.CharField(choices=[('INCOME', 'Ingreso'), ('DEDUCTION', 'Descuento'), ('CONTRIBUTION', 'Contribución')], max_length=12),
        ),
    ]
