# Generated by Django 6.0 on 2026-03-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_alter_payslipitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='effective_worked_days',
            field=models.IntegerField(default=22, verbose_name='Días Efectivos Laborados'),
        ),
    ]
