# Generated by Django 6.0 on 2026-03-13 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_institutionaldata_entry_date'),
        ('payroll', '0016_payslip_effective_worked_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='priority',
            field=models.IntegerField(default=100, help_text='Menor número = Se cobra primero. Ej: 1=IESS, 2=Retención Judicial, 10=Cooperativa', verbose_name='Prioridad de Cobro'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='effective_worked_days',
            field=models.IntegerField(default=0, verbose_name='Días Efectivos Laborados'),
        ),
        migrations.CreateModel(
            name='PendingDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Original')),
                ('collected_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('pending_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Pendiente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deduction_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction', verbose_name='Descuento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_debts', to='employee.employee', verbose_name='Empleado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_debts', to='payroll.payrollperiod', verbose_name='Periodo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'db_table': 'payroll_pending_debt',
            },
        ),
    ]
