# Generated by Django 6.0 on 2026-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_deduction_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_withheld',
            field=models.BooleanField(default=False, help_text='Si es True, este rol no saldrá en los reportes de transferencia bancaria', verbose_name='Pago Retenido'),
        ),
    ]
