# Generated by Django 6.0 on 2026-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_payslip_is_withheld'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalcontribution',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
