# Generated by Django 6.0 on 2026-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_institutionalcontribution_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Si es True, este rol ya se envió en un archivo SPI-SP y no debe volver a salir en los alcances.', verbose_name='Pagado / Enviado al Banco'),
        ),
    ]
