# Generated by Django 6.0 on 2026-03-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_payslip_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconstant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
