# Generated by Django 6.0 on 2026-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_payrollconstant_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslipitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='deduction',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Orden de Presentación'),
        ),
        migrations.AddField(
            model_name='income',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Orden de Presentación'),
        ),
        migrations.AddField(
            model_name='institutionalcontribution',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Orden de Presentación'),
        ),
        migrations.AddField(
            model_name='payslipitem',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Orden de Presentación'),
        ),
    ]
