# Generated by Django 6.0 on 2026-06-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_order_account_unique_active_account_order'),
        ('payroll', '0023_deduction_abbreviation_income_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Si se llena, generará un asiento de devengado automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_incomes', to='accounting.account', verbose_name='Cuenta HABER (Ingreso para Devengado)'),
        ),
    ]
