# Generated by Django 6.0 on 2026-06-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_order_account_unique_active_account_order'),
        ('employee', '0010_teleworkactivity'),
        ('payroll', '0024_deduction_income_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='debit_account',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='income_account',
        ),
        migrations.RemoveField(
            model_name='pendingdebt',
            name='deduction_ref',
        ),
        migrations.RemoveField(
            model_name='payslipitem',
            name='deduction_ref',
        ),
        migrations.RemoveField(
            model_name='income',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='debit_account',
        ),
        migrations.RemoveField(
            model_name='payslipitem',
            name='income_ref',
        ),
        migrations.RemoveField(
            model_name='institutionalcontribution',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='institutionalcontribution',
            name='debit_account',
        ),
        migrations.RemoveField(
            model_name='payslipitem',
            name='contribution_ref',
        ),
        migrations.AlterField(
            model_name='payslipitem',
            name='item_type',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='PayrollRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('DEDUCTION', 'Descuento/Egreso'), ('CONTRIBUTION', 'Aportes Institucionales')], max_length=15, verbose_name='Tipo de Rubro')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=100)),
                ('priority', models.IntegerField(blank=True, default=100, null=True)),
                ('has_mapping', models.BooleanField(default=False, verbose_name='¿Afecta al Presupuesto?')),
                ('dynamic_suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sufijo Presupuestario')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='¿Es Partida Fija?')),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_credits_corr', to='accounting.account')),
                ('credit_account_inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_credits_inv', to='accounting.account')),
                ('credit_account_prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_credits_prod', to='accounting.account')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_debits_corr', to='accounting.account')),
                ('debit_account_inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_debits_inv', to='accounting.account')),
                ('debit_account_prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_debits_prod', to='accounting.account')),
                ('income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_incomes', to='accounting.account')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='payrollnovelty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payrollnovelty',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrubric', verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='payslipitem',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollrubric'),
        ),
        migrations.AddField(
            model_name='pendingdebt',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrubric', verbose_name='Descuento'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollnovelty',
            unique_together={('period', 'employee', 'rubric')},
        ),
        migrations.DeleteModel(
            name='RubroBudgetMapping',
        ),
        migrations.DeleteModel(
            name='InstitutionalContribution',
        ),
        migrations.RemoveField(
            model_name='payrollnovelty',
            name='deduction_ref',
        ),
        migrations.RemoveField(
            model_name='payrollnovelty',
            name='income_ref',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
