# Generated by Django 6.0 on 2026-06-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_remove_deduction_credit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrubric',
            name='is_salary',
            field=models.BooleanField(default=False, help_text='Marque esta casilla solo para el rubro que represente el Sueldo Mensual Base.', verbose_name='¿Es Sueldo / Remuneración Base?'),
        ),
    ]
