# Generated by Django 6.0 on 2026-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_payrollrubric_is_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrubric',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
