# Generated by Django 6.0 on 2026-06-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_alter_payrollrubric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrubric',
            name='spending_context',
            field=models.CharField(choices=[('TODOS', '1. Todos (Universal)'), ('5.1', '2. Corriente (5.1)'), ('7.1', '3. Inversión (7.1)'), ('6.1', '4. Producción (6.1)')], default='TODOS', max_length=10, verbose_name='Contexto de Gasto'),
        ),
    ]
