# Generated by Django 6.0 on 2026-06-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_payrollrubric_spending_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrubric',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='Marque si este rubro (ej. Subrogación, Horas Extra) es base imponible.', verbose_name='¿Suma para IESS y Fondos de Reserva?'),
        ),
        migrations.AddField(
            model_name='payrollrubric',
            name='multiplier_factor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 1.50 (Extras) o 2.00 (Suplementarias). Si es mayor a 0, el sistema leerá el Excel como CANTIDAD DE HORAS, no como dinero.', max_digits=5, verbose_name='Factor Multiplicador de Horas'),
        ),
    ]
