# Generated by Django 6.0 on 2026-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_payrollrubric_is_taxable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrubric',
            name='multiplier_factor',
        ),
        migrations.AddField(
            model_name='payrollrubric',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Marque si el Excel de este rubro debe leer la Columna B (1.50) y Col C (2.00) como horas.', verbose_name='¿Es Rubro de Horas Extras/Suplementarias?'),
        ),
    ]
