# Generated by Django 6.0 on 2026-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_remove_payrollrubric_multiplier_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrubric',
            name='is_upload',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Carga masiva?'),
        ),
    ]
