# Generated by Django 6.0 on 2025-12-15 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee/photos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Personal')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('address_reference', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('has_catastrophic_illness', models.BooleanField(default=False)),
                ('catastrophic_illness_description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_substitute', models.BooleanField(default=False)),
                ('substitute_family_member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('substitute_family_member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute_family_member_disability_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'BLOOD_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_blood_type', to='core.catalogitem', verbose_name='Tipo de Sangre')),
                ('canton', models.ForeignKey(blank=True, limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_canton', to='core.location')),
                ('country', models.ForeignKey(blank=True, limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_country', to='core.location')),
                ('disability_type', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'DISABILITY_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_disability', to='core.catalogitem')),
                ('document_type', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'DOCUMENT_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_document_type', to='core.catalogitem')),
                ('emergency_contact_relationship', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'RELATIONSHIPS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_contacts_by_relationship', to='core.catalogitem')),
                ('gender', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'GENDERS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_gender', to='core.catalogitem', verbose_name='Género')),
                ('marital_status', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'MARITAL_STATUSES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_marital_status', to='core.catalogitem', verbose_name='Estado Civil')),
                ('parish', models.ForeignKey(blank=True, limit_choices_to={'level': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_parish', to='core.location')),
                ('person_status', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'PERSON_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_status', to='core.catalogitem', verbose_name='Estado')),
                ('province', models.ForeignKey(blank=True, limit_choices_to={'level': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_by_province', to='core.location')),
                ('substitute_family_member_disability_type', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'DISABILITY_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutes_by_disability', to='core.catalogitem')),
                ('substitute_family_member_relationship', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'RELATIONSHIPS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutes_by_relationship', to='core.catalogitem')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
