# Generated by Django 6.0 on 2026-02-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono'),
        ),
    ]
