# Generated by Django 6.0 on 2026-04-09 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_emergency_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Revisó'), ('UPDATE', 'Actualizó'), ('PHOTO', 'Cambió Foto')], max_length=20, verbose_name='Acción')),
                ('section', models.CharField(blank=True, max_length=120, null=True, verbose_name='Sección')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='person.person', verbose_name='Persona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Persona',
                'verbose_name_plural': 'Auditorías de Persona',
                'ordering': ['-created_at'],
            },
        ),
    ]
