# Generated by Django 6.0 on 2025-12-24 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Código Partida')),
                ('number_individual', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Partida Individual')),
                ('remuneration', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='RMU')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='budget.activity', verbose_name='Actividad')),
                ('category_item', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'BUDGET_CATEGORY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines_category', to='core.catalogitem', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('current_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_budget_line', to='employee.employee', verbose_name='Custodio/Ocupante')),
                ('grade_item', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'BUDGET_GRADE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines_grade', to='core.catalogitem', verbose_name='Grado')),
                ('group_item', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'BUDGET_GROUP'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines_group', to='core.catalogitem', verbose_name='Grupo Ocupacional')),
                ('position_item', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'JOB_POSITIONS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines_position', to='core.catalogitem', verbose_name='Cargo Estructural')),
                ('regime_item', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'LABOR_REGIMES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines_regime', to='core.catalogitem', verbose_name='Régimen Laboral')),
                ('spending_type_item', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'BUDGET_SPENDING_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines_spending', to='core.catalogitem', verbose_name='Tipo de Gasto')),
                ('status_item', models.ForeignKey(limit_choices_to={'catalog__code': 'BUDGET_STATUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines_status', to='core.catalogitem', verbose_name='Estado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Partidas Presupuestarias',
                'ordering': ['code', 'number_individual'],
                'permissions': [('view_salary', 'Puede ver remuneraciones')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Área-Programa',
                'verbose_name_plural': 'Áreas-Programas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='budget.project', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='Subprogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subprograms', to='budget.program', verbose_name='Área/Programa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Subprograma',
                'verbose_name_plural': 'Subprogramas',
                'ordering': ['code'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='subprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='budget.subprogram', verbose_name='Subprograma'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('project', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('subprogram', 'code')},
        ),
    ]
