# Generated by Django 6.0 on 2026-01-07 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.CreateModel(
            name='BudgetAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Es asignación actual')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación de salida')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='budget.budgetline', verbose_name='Partida')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_history', to='employee.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Historial de Asignación',
                'verbose_name_plural': 'Historiales de Asignaciones',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetModificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificación')),
                ('modification_type', models.CharField(blank=True, choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('STATUS_CHANGE', 'Cambio de Estado'), ('ASSIGNMENT', 'Asignación de Persona'), ('RELEASE', 'Liberación de Persona')], max_length=50, null=True, verbose_name='Tipo de Modificación')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo modificado')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo del Cambio')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifications', to='budget.budgetline', verbose_name='Partida')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Historial de Modificación',
                'verbose_name_plural': 'Historiales de Modificaciones',
                'ordering': ['-modification_date'],
            },
        ),
    ]
