# Generated by Django 6.0 on 2026-03-12 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_activity_is_active_alter_program_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('base_code', models.CharField(max_length=50, unique=True, verbose_name='Código Base (Sin secuencial)')),
                ('short_code', models.CharField(max_length=15, unique=True, verbose_name='Código Corto (TH)')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Agrupación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Agrupación de Rol',
                'verbose_name_plural': 'Agrupaciones de Roles',
                'ordering': ['short_code'],
            },
        ),
        migrations.AddField(
            model_name='budgetline',
            name='budget_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='budget.budgetgroup', verbose_name='Agrupación de Rol'),
        ),
    ]
