# Generated by Django 6.0 on 2026-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetgroup_budgetline_budget_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetassignmenthistory',
            name='is_acting',
            field=models.BooleanField(default=False, verbose_name='Es Encargo / Subrogación'),
        ),
    ]
