# Generated by Django 6.0 on 2026-01-16 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_authorities'),
        ('employee', '0003_alter_employee_is_boss_curriculum_academictitle_and_more'),
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Catálogo')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código Interno')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Catálogo de Manual',
                'verbose_name_plural': 'Catálogos de Manual',
            },
        ),
        migrations.CreateModel(
            name='ManualCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Item')),
                ('code', models.CharField(max_length=100, verbose_name='Código Técnico')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción/Observación')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='function_manual.manualcatalog', verbose_name='Catálogo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Item de Catálogo',
                'verbose_name_plural': 'Items de Catálogo',
                'ordering': ['catalog', 'order', 'name'],
                'unique_together': {('catalog', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('position_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Posicional')),
                ('specific_job_title', models.CharField(max_length=255, verbose_name='Cargo Específico')),
                ('mission', models.TextField(verbose_name='Misión')),
                ('interface_relations', models.TextField(verbose_name='Relaciones Internas/Externas')),
                ('knowledge_area', models.TextField(verbose_name='Área de Conocimiento')),
                ('required_experience_months', models.PositiveIntegerField(default=0, verbose_name='Experiencia (Meses)')),
                ('experience_details', models.TextField(verbose_name='Detalle de Experiencia')),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_profiles', to='institution.administrativeunit', verbose_name='Unidad Administrativa')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_profiles', to='core.authorities')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_profiles', to='core.authorities')),
                ('referential_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Empleado Referencial')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_profiles', to='core.authorities')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('decision_making', models.ForeignKey(limit_choices_to={'catalog__code': 'DECISION_LEVELS'}, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_decision', to='function_manual.manualcatalogitem', verbose_name='Toma de Decisiones')),
                ('final_complexity_level', models.ForeignKey(limit_choices_to={'catalog__code': 'COMPLEXITY_LEVELS'}, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_complexity', to='function_manual.manualcatalogitem', verbose_name='Complejidad Resultante')),
                ('job_role', models.ForeignKey(limit_choices_to={'catalog__code': 'JOB_ROLES'}, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_role', to='function_manual.manualcatalogitem', verbose_name='Rol Asignado')),
                ('management_impact', models.ForeignKey(limit_choices_to={'catalog__code': 'IMPACT_LEVELS'}, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_impact', to='function_manual.manualcatalogitem', verbose_name='Impacto de Gestión')),
                ('required_instruction', models.ForeignKey(limit_choices_to={'catalog__code': 'INSTRUCTION_LEVELS'}, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_instruction', to='function_manual.manualcatalogitem', verbose_name='Nivel de Instrucción')),
            ],
            options={
                'verbose_name': 'Perfil de Puesto',
                'verbose_name_plural': 'Perfiles de Puesto',
            },
        ),
        migrations.CreateModel(
            name='JobActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='function_manual.jobprofile')),
                ('action_verb', models.ForeignKey(limit_choices_to={'catalog__code': 'ACTION_VERBS'}, on_delete=django.db.models.deletion.PROTECT, related_name='activity_action_verbs', to='function_manual.manualcatalogitem', verbose_name='Verbo de Acción')),
                ('frequency', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'FREQUENCY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_frequencies', to='function_manual.manualcatalogitem', verbose_name='Frecuencia')),
            ],
            options={
                'verbose_name': 'Actividad Esencial',
                'verbose_name_plural': 'Actividades Esenciales',
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Competencia')),
                ('type', models.CharField(choices=[('TECHNICAL', 'Técnica'), ('BEHAVIORAL', 'Conductual'), ('TRANSVERSAL', 'Transversales')], max_length=20, verbose_name='Tipo')),
                ('definition', models.TextField(verbose_name='Definición de la Competencia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('suggested_level', models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'COMPLEXITY_LEVELS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='function_manual.manualcatalogitem', verbose_name='Nivel Sugerido')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Diccionario de Competencias',
            },
        ),
        migrations.CreateModel(
            name='OccupationalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('occupational_group', models.CharField(max_length=100, verbose_name='Grupo Ocupacional (Ej: SP1)')),
                ('grade', models.PositiveIntegerField(verbose_name='Grado de la Escala')),
                ('remuneration', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='R.M.U.')),
                ('minimum_experience_months', models.PositiveIntegerField(verbose_name='Experiencia Mínima (Meses)')),
                ('complexity_level', models.ForeignKey(limit_choices_to={'catalog__code': 'COMPLEXITY_LEVELS'}, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_by_complexities', to='function_manual.manualcatalogitem', verbose_name='Nivel de Complejidad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('minimum_instruction', models.ForeignKey(limit_choices_to={'catalog__code': 'INSTRUCTION_LEVELS'}, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_by_instructions', to='function_manual.manualcatalogitem', verbose_name='Instrucción Formal Mínima')),
                ('required_role', models.ForeignKey(limit_choices_to={'catalog__code': 'JOB_ROLES'}, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_by_roles', to='function_manual.manualcatalogitem', verbose_name='Rol del Puesto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Matriz Ocupacional',
                'verbose_name_plural': 'Matrices Ocupacionales',
                'unique_together': {('occupational_group', 'grade')},
            },
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='occupational_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='function_manual.occupationalmatrix', verbose_name='Clasificación Matriz'),
        ),
        migrations.CreateModel(
            name='ProfileCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observable_behavior', models.TextField(verbose_name='Comportamiento Observable')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function_manual.competency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function_manual.jobprofile')),
            ],
            options={
                'verbose_name': 'Competencia del Perfil',
                'verbose_name_plural': 'Competencias del Perfil',
            },
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='competencies',
            field=models.ManyToManyField(through='function_manual.ProfileCompetency', to='function_manual.competency'),
        ),
    ]
