# Generated by Django 6.0 on 2026-01-16 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('node_type', models.CharField(choices=[('ROLE', 'Rol de Puesto'), ('INSTRUCTION', 'Instrucción Formal'), ('EXPERIENCE', 'Experiencia'), ('DECISION', 'Nivel de Decisiones'), ('IMPACT', 'Nivel de Impacto'), ('COMPLEXITY', 'Nivel de Complejidad'), ('RESULT', 'Grupo Ocupacional (Resultado)')], max_length=20, verbose_name='Tipo de Nivel')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='function_manual.manualcatalogitem', verbose_name='Valor del Catálogo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('occupational_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='function_manual.occupationalmatrix', verbose_name='Clasificación Salarial')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='function_manual.valuationnode', verbose_name='Nodo Padre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Nodo de Valoración',
                'verbose_name_plural': 'Estructura de Valoración',
                'ordering': ['node_type', 'catalog_item__order'],
            },
        ),
    ]
