# Generated by Django 6.0 on 2026-01-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0002_valuationnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationnode',
            name='name_extra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción personalizada'),
        ),
    ]
