# Generated by Django 6.0 on 2026-01-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0003_valuationnode_name_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationalmatrix',
            name='required_decision',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'DECISION_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_by_decisions', to='function_manual.manualcatalogitem', verbose_name='Nivel de Decisiones'),
        ),
        migrations.AddField(
            model_name='occupationalmatrix',
            name='required_impact',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'IMPACT_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_by_impact', to='function_manual.manualcatalogitem', verbose_name='Nivel de Impacto'),
        ),
    ]
