# Generated by Django 6.0 on 2026-01-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0004_occupationalmatrix_required_decision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualcatalogitem',
            options={'ordering': ['catalog', 'name'], 'verbose_name': 'Item de Catálogo', 'verbose_name_plural': 'Items de Catálogo'},
        ),
        migrations.AlterModelOptions(
            name='valuationnode',
            options={'ordering': ['node_type'], 'verbose_name': 'Nodo de Valoración', 'verbose_name_plural': 'Estructura de Valoración'},
        ),
        migrations.RemoveField(
            model_name='jobactivity',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='manualcatalogitem',
            name='order',
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='additional_knowledge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Conocimientos Adicionales'),
        ),
        migrations.AddField(
            model_name='manualcatalogitem',
            name='target_groups',
            field=models.CharField(blank=True, max_length=255, verbose_name='Grupos Ocupacionales (Separados por coma)'),
        ),
    ]
