# Generated by Django 6.0 on 2026-01-20 00:00

from django.db import migrations, models


def forwards(apps, schema_editor):
    ManualCatalogItem = apps.get_model('function_manual', 'ManualCatalogItem')
    ValuationNode = apps.get_model('function_manual', 'ValuationNode')

    role_nodes = ValuationNode.objects.filter(node_type='ROLE', catalog_item_id__isnull=False)
    role_map = {}
    for node in role_nodes:
        role_map.setdefault(node.catalog_item_id, []).append(node.id)

    for item in ManualCatalogItem.objects.all():
        tg = (item.target_groups or '').strip()
        if not tg or tg.upper() == 'TODOS':
            continue
        node_ids = []
        for part in tg.split(','):
            part = part.strip()
            if part.isdigit():
                role_id = int(part)
                node_ids.extend(role_map.get(role_id, []))
        if node_ids:
            item.target_roles.add(*node_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0005_alter_manualcatalogitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcatalogitem',
            name='target_roles',
            field=models.ManyToManyField(
                blank=True,
                related_name='catalog_items',
                to='function_manual.valuationnode',
                limit_choices_to={'node_type': 'ROLE'},
                verbose_name='Roles Permitidos (Estructura de Valoración)'
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='manualcatalogitem',
            name='target_groups',
        ),
    ]
