# Generated by Django 6.0 on 2026-01-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0005_alter_manualcatalogitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='training_topic',
            field=models.TextField(blank=True, null=True, verbose_name='Temática de Capacitación'),
        ),
        migrations.AlterField(
            model_name='profilecompetency',
            name='observable_behavior',
            field=models.TextField(blank=True, null=True, verbose_name='Comportamiento Observable'),
        ),
    ]
