# Generated by Django 6.0 on 2026-01-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0006_jobprofile_training_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='legalized_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/legalized/', verbose_name='Perfil Legalizado (Escaneado)'),
        ),
    ]
