# Generated by Django 6.0 on 2026-01-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0007_jobprofile_legalized_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='decision_making',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'DECISION_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_decision', to='function_manual.manualcatalogitem', verbose_name='Toma de Decisiones'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='final_complexity_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'COMPLEXITY_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_complexity', to='function_manual.manualcatalogitem', verbose_name='Complejidad Resultante'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_role',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'JOB_ROLES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_role', to='function_manual.manualcatalogitem', verbose_name='Rol Asignado'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='management_impact',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'IMPACT_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_impact', to='function_manual.manualcatalogitem', verbose_name='Impacto de Gestión'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='required_instruction',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'INSTRUCTION_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_instruction', to='function_manual.manualcatalogitem', verbose_name='Nivel de Instrucción'),
        ),
    ]
