# Generated by Django 6.0 on 2026-01-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0006_manualcatalogitem_target_roles'),
        ('function_manual', '0008_alter_jobprofile_decision_making_and_more'),
    ]

    operations = [
    ]
