# Generated by Django 6.0 on 2026-01-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0009_merge_20260120_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualcatalogitem',
            name='target_roles',
        ),
        migrations.AddField(
            model_name='manualcatalogitem',
            name='target_role',
            field=models.ForeignKey(blank=True, limit_choices_to={'node_type': 'ROLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='function_manual.valuationnode', verbose_name='Rol Permitido (Estructura de Valoración)'),
        ),
    ]
