# Generated by Django 6.0 on 2026-01-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0010_remove_manualcatalogitem_target_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'permissions': [('can_admin', 'Puede administrar Competencias')], 'verbose_name': 'Competencia', 'verbose_name_plural': 'Diccionario de Competencias'},
        ),
        migrations.AlterModelOptions(
            name='jobprofile',
            options={'permissions': [('can_admin', 'Puede administrar Perfiles de Puesto')], 'verbose_name': 'Perfil de Puesto', 'verbose_name_plural': 'Perfiles de Puesto'},
        ),
        migrations.AlterModelOptions(
            name='manualcatalog',
            options={'permissions': [('can_admin', 'Puede administrar Catálogos de Manual')], 'verbose_name': 'Catálogo de Manual', 'verbose_name_plural': 'Catálogos de Manual'},
        ),
        migrations.AlterModelOptions(
            name='occupationalmatrix',
            options={'permissions': [('can_admin', 'Puede administrar Matriz Ocupacional')], 'verbose_name': 'Matriz Ocupacional', 'verbose_name_plural': 'Matrices Ocupacionales'},
        ),
        migrations.AlterModelOptions(
            name='valuationnode',
            options={'ordering': ['node_type'], 'permissions': [('can_admin', 'Puede administrar Estructura de Valoración')], 'verbose_name': 'Nodo de Valoración', 'verbose_name_plural': 'Estructura de Valoración'},
        ),
    ]
