# Generated by Django 6.0 on 2026-01-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0011_alter_competency_options_alter_jobprofile_options_and_more'),
        ('institution', '0003_remove_deliverable_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobactivity',
            name='complexity',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'COMPLEXITY_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities_complexity', to='function_manual.manualcatalogitem', verbose_name='Nivel de Complejidad'),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='contribution',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'COMPLEXITY_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities_contribution', to='function_manual.manualcatalogitem', verbose_name='Aporte a la Gestión'),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='institution.deliverable', verbose_name='Entregable / Producto'),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='frequency',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'FREQUENCY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities_frequency', to='function_manual.manualcatalogitem', verbose_name='Frecuencia'),
        ),
    ]
