# Generated by Django 6.0 on 2026-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0012_jobactivity_complexity_jobactivity_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobactivity',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos de Actividad'),
        ),
    ]
