# Generated by Django 6.0 on 2026-01-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_payrollinfo_roles_count'),
        ('function_manual', '0013_jobactivity_points'),
        ('institution', '0004_alter_administrativeunit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobprofile',
            options={'verbose_name': 'Perfil de Puesto', 'verbose_name_plural': 'Perfiles de Puesto'},
        ),
        migrations.AlterModelOptions(
            name='occupationalmatrix',
            options={'ordering': ['grade'], 'verbose_name': 'Matriz Ocupacional', 'verbose_name_plural': 'Matrices Ocupacionales'},
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='required_experience_months',
        ),
        migrations.RemoveField(
            model_name='occupationalmatrix',
            name='complexity_level',
        ),
        migrations.RemoveField(
            model_name='occupationalmatrix',
            name='minimum_experience_months',
        ),
        migrations.RemoveField(
            model_name='occupationalmatrix',
            name='minimum_instruction',
        ),
        migrations.RemoveField(
            model_name='occupationalmatrix',
            name='required_decision',
        ),
        migrations.RemoveField(
            model_name='occupationalmatrix',
            name='required_impact',
        ),
        migrations.RemoveField(
            model_name='occupationalmatrix',
            name='required_role',
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='required_experience',
            field=models.CharField(default='No Requerida', max_length=255, verbose_name='Experiencia Requerida'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='administrative_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_profiles', to='institution.administrativeunit'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='decision_making',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'DECISION_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_decision', to='function_manual.manualcatalogitem'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='final_complexity_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'COMPLEXITY_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_complexity', to='function_manual.manualcatalogitem'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_role',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'JOB_ROLES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_role', to='function_manual.manualcatalogitem'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='legalized_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/legalized/'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='management_impact',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'IMPACT_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_impact', to='function_manual.manualcatalogitem'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='position_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='referential_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='required_instruction',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog__code': 'INSTRUCTION_LEVELS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_instruction', to='function_manual.manualcatalogitem'),
        ),
    ]
