# Generated by Django 6.0 on 2026-03-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authority_model_migration'),
        ('function_manual', '0014_alter_jobprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_profiles', to='core.authority'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_profiles', to='core.authority'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_profiles', to='core.authority'),
        ),
    ]
