# Generated by Django 6.0 on 2026-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0015_alter_jobprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuationnode',
            name='node_type',
            field=models.CharField(choices=[('ROLE', 'Rol de Puesto'), ('INSTRUCTION', 'Instrucción Formal'), ('EXPERIENCE', 'Experiencia'), ('DECISION', 'Nivel de Decisiones'), ('IMPACT', 'Nivel de Impacto'), ('COMPLEXITY', 'Nivel de Complejidad'), ('RESULT', 'Grupo Ocupacional (Resultado)'), ('GENERIC_DENOMINATION', 'Denominación Genérica')], max_length=20, verbose_name='Tipo de Nivel'),
        ),
    ]
