# Generated by Django 6.0 on 2026-03-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0016_alter_valuationnode_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationnode',
            name='minimum_value',
            field=models.PositiveIntegerField(blank=True, help_text='Valor mínimo para este nivel (sin decimales)', null=True, verbose_name='Valor Mínimo'),
        ),
    ]
