# Generated by Django 6.0 on 2026-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0017_valuationnode_minimum_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='specific_job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo Específico'),
        ),
    ]
