# Generated by Django 6.0 on 2026-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0018_alter_jobprofile_specific_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='total_activity_points',
            field=models.PositiveIntegerField(default=0, help_text='Suma de puntos de las primeras 6 actividades', verbose_name='Total Puntos Actividades'),
        ),
    ]
