# Generated by Django 6.0 on 2026-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0019_jobprofile_total_activity_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='denomination_completed',
            field=models.BooleanField(default=False, help_text='Indica si la denominación del cargo fue editada por el usuario', verbose_name='Denominación Completada'),
        ),
    ]
