# Generated by Django 6.0 on 2026-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0020_jobprofile_denomination_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Nivel asociado al grupo ocupacional resultante', null=True, verbose_name='Nivel del Cargo'),
        ),
        migrations.AddField(
            model_name='valuationnode',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Nivel asociado al grupo ocupacional (solo para Resultado Final)', null=True, verbose_name='Nivel'),
        ),
    ]
