# Generated by Django 6.0 on 2026-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0021_jobprofile_level_valuationnode_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='is_legalized',
            field=models.BooleanField(default=False, help_text='Indica si el perfil de puesto fue legalizado', verbose_name='Legalizado'),
        ),
    ]
