# Generated by Django 6.0 on 2026-04-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0022_jobprofile_is_legalized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE function_manual_jobprofile
                SET prepared_by_id = NULL,
                    reviewed_by_id = NULL,
                    approved_by_id = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
