# Generated by Django 6.0 on 2026-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_manual', '0023_alter_jobprofile_approved_by_and_more'),
        ('institution', '0004_alter_administrativeunit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobactivity',
            name='deliverable',
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='deliverables',
            field=models.ManyToManyField(blank=True, related_name='activities', to='institution.deliverable', verbose_name='Entregables / Productos'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='total_activity_points',
            field=models.PositiveIntegerField(default=0, help_text='Suma de puntos de las actividades', verbose_name='Total Puntos Actividades'),
        ),
    ]
